### ISSUE TITLE
Some code example of spatio temporal models?

### ISSUE THREAD

**Issue by ZifengDing** [Zymrael/gde#1]
Hi,

Very impressed by your work.
I am very interested in the part about spatio temporal models in your literature. Especially some tasks about temporal prediction, e.g. traffic forecasting. 
Could you please open source this part of code? (Or maybe just send me by email :))That would be a great help and inspiration.

And also, could you please also send the code about GAT ode layer?

**Comment by Zymrael** [comment]
Hi @Woolaowu, closing this as I have sent you GCDE scripts via email :)

For further development of GDE model variants refer to the [torchdyn](https://github.com/DiffEqML/torchdyn) library. You're also welcome to contribute with tutorials or model variants!

**Comment by CongWeilin** [comment]
Sorry to bother, I found this thread related to what I want.

Could you please also share the code for running GDE for traffic forecasting? Thanks.

**Comment by DLwbm123** [comment]
Could you please also send me the code GDE for spatio-temporal modeling ? Thanks.

**Comment by jeongwhanchoi** [comment]
Could you please also share me the code GDE for spatio-temporal modeling?

**Comment by fakeProgrammer0** [comment]
Hi, @Zymrael 
The part of Spatio-Temporal Models in your work really catches my interests. I would be very appreciated if you could also send me the code of this part by email. My email address is [chenlj69@mail2.sysu.edu.cn](chenlj69@mail2.sysu.edu.cn) . Thanks a lot : )

**Comment by idevede** [comment]
Hi, @Zymrael. Thanks for the promising work! Interested in the part of Spatio-Temporal Models, could you please send me the code of this part to: 1801213647@pku.edu.cn. Best!

**Comment by kartikeyas00** [comment]
Hi @Zymrael I am also very interested in Spatio-Temporal Models, would it be possible to send me the code at ksharma2@uoregon.edu

Regards,
Kartikeya

**Comment by binchen4110** [comment]
Hi,  @Zymrael . Thanks for the promising work! Interested in the part of Spatio-Temporal Models, could you please send me the code of this part to: [binchen4110@gmail.com](mailto:binchen4110@gmail.com). Best!

**Comment by wang422003** [comment]
Hi guys! I need your help! I am also interested in the part of Spatio-Temporal Models, fo anyone of you have the code?
